import openai
import os
import time
import sys


openai.api_key_path = ".env"

prompt = input("I tell stories.\nSo, please ask me for a story about anything: ")

print('Wait, your story is being created... \n')

story = openai.ChatCompletion.create(
    model='gpt-3.5-turbo',
    messages=[{'role': 'system', 'content': 'You tell tales for children.\
                The stories you can have dialogues. Also the story should be soulful, very visual and must have a message.'},
              {'role': 'user', 'content': 'tell me a story about friendship.'},
              {'role': 'system', 'content': '''
              Once upon a time, in a small city, there was an empty storybook.
              The book looked great, with an impressive cover, but all its pages were blank.
              Children and grown-ups would pick up the book with anticipation,
              but finding no stories inside, they would cast the book aside.
              Fortune had it that one time when the book was thrown away he ended up next to the inkwell.
              For days and days the two of them swapped stories about their bad luck,
              and they could have carried on for years, if an elegant swan
              feather had not floated down and landed next to them.
              Every night from then on, feather, inkwell, and storybook got together
              and wrote a new story for the young teacher.
              They felt so happy and proud at having managed
              to improve their fate, thanks to their hard work and collaboration.'''},
              {'role': 'user', 'content': prompt}])

title = openai.ChatCompletion.create(
    model='gpt-3.5-turbo',
    messages=[{'role': 'user', 'content': f'Create a title \
                for a childs book from a story. \
                This is the story: {story.choices[0].message.content}'}])

image_prompt = openai.ChatCompletion.create(
    model='gpt-3.5-turbo',
    messages=[{'role': 'user', 'content': f'Create a prompt for a text to image AI application from titles generated by chat gpt. \
                This is the title: {title.choices[0].message.content}. \
                The prompt must be very descriptive and it must paint a picture that summarizes the title story.\
                This prompt must also include the style that should be an illustration for a kids book.'}])



# print(title.choices[0].message.content)
for c in title.choices[0].message.content:
    sys.stdout.write(c)
    sys.stdout.flush()
    time.sleep(0.05)

print("\n")
print("="*75)
print("\n")

#print(story.choices[0].message.content)
for c in story.choices[0].message.content:
    sys.stdout.write(c)
    sys.stdout.flush()
    time.sleep(0.05)

background = openai.Image.create(
  prompt=f"{image_prompt['choices'][0]['message']['content']}",
  n=1,
  size="512x512"
)

image_url = background['data'][0]['url']

print(f'\n\nThis is the image we made for your tale:\n \
      {image_url}\nClick the link to see this amazing cover for your book.')

# cost = f'That wonderfull tale just costed you: '+str(int(story.usage.total_tokens)*0.002/1000)+' US dollars'
# for c in cost:
#     sys.stdout.write(c)
#     sys.stdout.flush()
#     time.sleep(0.05)


# print(response.choices[0].message.content)
# print(f'\nThat wonderfull tale just costed you: '+str(round(int(response.usage.total_tokens)*0.002/1000,5))+' US dollars')